language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgif-dev
      - g++-4.8
before_script:
  - npm run lint
  - sudo apt-get install imagemagick
  - phantomjs examplesToPng.js
  - npm install gulp
script:
  - gulp
  - npm test
  - ./magick.sh
