language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgif-dev
      - g++-4.8
before_script:
  - npm run lint
  - npm install -g minimatch@3.0.4
  - npm install -g gulp
script:
  - gulp
  - npm test
